#!/usr/bin/env bash

prefix="vcw_module_hkvb_registry_traefik__$1"
prefix="vcw_module_hkvb_registry_traefik__$1"

if [[ "vcw_module_hkvb_registry_traefik__registry_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_registry_traefik__registry_data_volume
fi
